package utils

import (
	"time"

	"github.com/Chak-and-Jules/home-inventory-backend/internal/logger"
	"github.com/Chak-and-Jules/home-inventory-backend/internal/models"
	"github.com/google/uuid"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// UpdateShoppingListForDefinition checks the stock levels for a given item definition and updates the shopping list accordingly.
func UpdateShoppingListForDefinition(tx *gorm.DB, homeID uuid.UUID, itemDefID uuid.UUID) error {
	var itemDef models.ItemDefinition
	if err := tx.First(&itemDef, itemDefID).Error; err != nil {
		logger.Log.Error("Failed to fetch item definition", zap.Error(err))
		return err
	}

	var existingItem models.ShoppingListItem
	err := tx.Where("home_id = ? AND item_definition_id = ? AND is_auto_generated = ? AND is_bought = ?",
		homeID, itemDefID, true, false).First(&existingItem).Error

	// If no threshold is set, we don't auto-generate.
	// We also remove any existing auto-generated items that are not bought.
	if itemDef.LowStockThreshold == nil {
		if err == nil {
			return tx.Delete(&existingItem).Error
		}
		logger.Log.Error("Failed to fetch existing shopping list item", zap.Error(err))
		return nil
	}

	var totalQuantity float64
	if err := tx.Model(&models.InventoryItem{}).
		Where("home_id = ? AND item_definition_id = ? AND (expiration_date IS NULL OR expiration_date > NOW())", homeID, itemDefID).
		Select("COALESCE(SUM(quantity), 0)").
		Scan(&totalQuantity).Error; err != nil {
		logger.Log.Error("Failed to calculate total quantity", zap.Error(err))
		return err
	}

	if totalQuantity <= *itemDef.LowStockThreshold {
		// Needs to be on the shopping list
		neededQuantity := 1.0
		if itemDef.TargetQuantity != nil {
			neededQuantity = *itemDef.TargetQuantity - totalQuantity
			if neededQuantity <= 0 {
				neededQuantity = 1.0 // Fallback if target is somehow less than current but still below threshold
			}
		}

		if err == gorm.ErrRecordNotFound {
			// Create new
			newItem := models.ShoppingListItem{
				HomeID:           homeID,
				ItemDefinitionID: &itemDefID,
				Name:             itemDef.Name,
				Quantity:         neededQuantity,
				IsAutoGenerated:  true,
				IsBought:         false,
			}
			if err := tx.Create(&newItem).Error; err != nil {
				logger.Log.Error("Failed to create shopping list item", zap.Error(err))
				return err
			}

			// AC 2.5: Trigger notification
			var home models.Home
			if err := tx.First(&home, homeID).Error; err == nil {
				SendLowStockNotification(homeID, home.Name, itemDef.Name, itemDef.Priority)
			} else {
				// Fallback if home not found for some reason
				SendLowStockNotification(homeID, homeID.String(), itemDef.Name, itemDef.Priority)
			}
			return nil
		} else if err == nil {
			// Update existing
			return tx.Model(&existingItem).Update("quantity", neededQuantity).Error
		}
		return err
	} else {
		// Should NOT be on the shopping list (auto-generated one)
		if err == nil {
			// Remove it
			return tx.Delete(&existingItem).Error
		} else if err == gorm.ErrRecordNotFound {
			return nil
		}
		return err
	}
}

// RefreshAllShoppingLists iterates over all item definitions and updates their shopping list status.
// This is useful for catching items that have expired since the last update.
func RefreshAllShoppingLists(db *gorm.DB) error {
	// Use FindInBatches for scalability
	var itemDefs []models.ItemDefinition
	err := db.FindInBatches(&itemDefs, 100, func(tx *gorm.DB, batch int) error {
		for _, def := range itemDefs {
			if err := db.Transaction(func(tx *gorm.DB) error {
				// AC: Also check for expiring soon items to send notifications
				threeDaysFromNow := time.Now().AddDate(0, 0, 3)
				var expiringSoonItems []models.InventoryItem
				if err := tx.Where("home_id = ? AND item_definition_id = ? AND expiration_date > NOW() AND expiration_date <= ?",
					def.HomeID, def.ID, threeDaysFromNow).Find(&expiringSoonItems).Error; err == nil {
					if len(expiringSoonItems) > 0 {
						var home models.Home
						if err := tx.First(&home, def.HomeID).Error; err == nil {
							for _, item := range expiringSoonItems {
								SendExpiryNotification(def.HomeID, home.Name, def.Name, item.ExpirationDate.Format("2006-01-02"))
							}
						} else {
							for _, item := range expiringSoonItems {
								SendExpiryNotification(def.HomeID, def.HomeID.String(), def.Name, item.ExpirationDate.Format("2006-01-02"))
							}
						}
					}
				}

				return UpdateShoppingListForDefinition(tx, def.HomeID, def.ID)
			}); err != nil {
				logger.Log.Error("Failed to refresh shopping list for definition",
					zap.String("item_definition_id", def.ID.String()),
					zap.Error(err))
				// Continue with others in the batch
			}
		}
		return nil
	}).Error

	if err != nil {
		logger.Log.Error("Failed to refresh shopping lists in batches", zap.Error(err))
		return err
	}

	return nil
}
