package utils

import (
	"time"

	"github.com/Chak-and-Jules/home-inventory-backend/internal/logger"
	"github.com/Chak-and-Jules/home-inventory-backend/internal/models"
	"github.com/google/uuid"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// UpdateShoppingListForDefinition checks the stock levels for a given item definition and updates the shopping list accordingly.
func UpdateShoppingListForDefinition(tx *gorm.DB, homeID uuid.UUID, itemDefID uuid.UUID) error {
	var itemDef models.ItemDefinition
	if err := tx.First(&itemDef, itemDefID).Error; err != nil {
		logger.Log.Error("Failed to fetch item definition", zap.Error(err))
		return err
	}

	var existingItem models.ShoppingListItem
	err := tx.Where("home_id = ? AND item_definition_id = ? AND is_auto_generated = ? AND is_bought = ?",
		homeID, itemDefID, true, false).First(&existingItem).Error

	// If no threshold is set, we don't auto-generate.
	// We also remove any existing auto-generated items that are not bought.
	if itemDef.LowStockThreshold == nil {
		if err == nil {
			return tx.Delete(&existingItem).Error
		}
		logger.Log.Error("Failed to fetch existing shopping list item", zap.Error(err))
		return nil
	}

	var totalQuantity float64
	if err := tx.Model(&models.InventoryItem{}).
		Where("home_id = ? AND item_definition_id = ? AND (expiration_date IS NULL OR expiration_date > NOW())", homeID, itemDefID).
		Select("COALESCE(SUM(quantity), 0)").
		Scan(&totalQuantity).Error; err != nil {
		logger.Log.Error("Failed to calculate total quantity", zap.Error(err))
		return err
	}

	if totalQuantity <= *itemDef.LowStockThreshold {
		// Needs to be on the shopping list
		neededQuantity := 1.0
		if itemDef.TargetQuantity != nil {
			neededQuantity = *itemDef.TargetQuantity - totalQuantity
			if neededQuantity <= 0 {
				neededQuantity = 1.0 // Fallback if target is somehow less than current but still below threshold
			}
		}

		if err == gorm.ErrRecordNotFound {
			// Create new
			newItem := models.ShoppingListItem{
				HomeID:           homeID,
				ItemDefinitionID: &itemDefID,
				Name:             itemDef.Name,
				Quantity:         neededQuantity,
				IsAutoGenerated:  true,
				IsBought:         false,
			}
			if err := tx.Create(&newItem).Error; err != nil {
				logger.Log.Error("Failed to create shopping list item", zap.Error(err))
				return err
			}

			// AC 2.5: Trigger notification
			SendLowStockNotification(tx, homeID, itemDef.Name, itemDef.Priority)
			return nil
		} else if err == nil {
			// Update existing
			return tx.Model(&existingItem).Update("quantity", neededQuantity).Error
		}
		return err
	} else {
		// Should NOT be on the shopping list (auto-generated one)
		if err == nil {
			// Remove it
			return tx.Delete(&existingItem).Error
		} else if err == gorm.ErrRecordNotFound {
			return nil
		}
		return err
	}
}

// RefreshAllShoppingLists iterates through all item definitions and refreshes the shopping lists.
// This is intended to be run periodically (e.g., daily) to catch items that expired.
func RefreshAllShoppingLists(db *gorm.DB) {
	logger.Log.Info("Starting daily shopping list refresh")
	now := time.Now()
	threeDaysFromNow := now.AddDate(0, 0, 3)

	// 1. Process expirations and notifications
	var expiringItems []models.InventoryItem
	if err := db.Where("expiration_date > ? AND expiration_date <= ?", now, threeDaysFromNow).
		Find(&expiringItems).Error; err == nil {
		for _, item := range expiringItems {
			var def models.ItemDefinition
			if err := db.First(&def, item.ItemDefinitionID).Error; err == nil {
				SendExpiryNotification(db, item.HomeID, def.Name, *item.ExpirationDate)
			}
		}
	}

	// 2. Refresh shopping lists using FindInBatches for scalability
	var itemDefs []models.ItemDefinition
	db.Model(&models.ItemDefinition{}).FindInBatches(&itemDefs, 100, func(tx *gorm.DB, batch int) error {
		for _, def := range itemDefs {
			UpdateShoppingListForDefinition(tx, def.HomeID, def.ID)
		}
		return nil
	})

	logger.Log.Info("Daily shopping list refresh completed")
}
