package utils

import (
	"github.com/Chak-and-Jules/home-inventory-backend/internal/logger"
	"github.com/Chak-and-Jules/home-inventory-backend/internal/models"
	"github.com/google/uuid"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// UpdateShoppingListForDefinition checks the stock levels for a given item definition and updates the shopping list accordingly.
func UpdateShoppingListForDefinition(tx *gorm.DB, homeID uuid.UUID, itemDefID uuid.UUID) error {
	var itemDef models.ItemDefinition
	if err := tx.First(&itemDef, itemDefID).Error; err != nil {
		logger.Log.Error("Failed to fetch item definition", zap.Error(err))
		return err
	}

	var existingItem models.ShoppingListItem
	err := tx.Where("home_id = ? AND item_definition_id = ? AND is_auto_generated = ? AND is_bought = ?",
		homeID, itemDefID, true, false).First(&existingItem).Error

	// If no threshold is set, we don't auto-generate.
	// We also remove any existing auto-generated items that are not bought.
	if itemDef.LowStockThreshold == nil {
		if err == nil {
			return tx.Delete(&existingItem).Error
		}
		logger.Log.Error("Failed to fetch existing shopping list item", zap.Error(err))
		return nil
	}

	var totalQuantity float64
	if err := tx.Model(&models.InventoryItem{}).
		Where("home_id = ? AND item_definition_id = ?", homeID, itemDefID).
		Select("COALESCE(SUM(quantity), 0)").
		Scan(&totalQuantity).Error; err != nil {
		logger.Log.Error("Failed to calculate total quantity", zap.Error(err))
		return err
	}

	if totalQuantity <= *itemDef.LowStockThreshold {
		// Needs to be on the shopping list
		neededQuantity := 1.0
		if itemDef.TargetQuantity != nil {
			neededQuantity = *itemDef.TargetQuantity - totalQuantity
			if neededQuantity <= 0 {
				neededQuantity = 1.0 // Fallback if target is somehow less than current but still below threshold
			}
		}

		if err == gorm.ErrRecordNotFound {
			// Create new
			newItem := models.ShoppingListItem{
				HomeID:           homeID,
				ItemDefinitionID: &itemDefID,
				Name:             itemDef.Name,
				Quantity:         neededQuantity,
				IsAutoGenerated:  true,
				IsBought:         false,
			}
			if err := tx.Create(&newItem).Error; err != nil {
				logger.Log.Error("Failed to create shopping list item", zap.Error(err))
				return err
			}

			// AC 2.5: Trigger notification
			SendLowStockNotification(homeID, itemDef.Name, itemDef.Priority)
			return nil
		} else if err == nil {
			// Update existing
			return tx.Model(&existingItem).Update("quantity", neededQuantity).Error
		}
		return err
	} else {
		// Should NOT be on the shopping list (auto-generated one)
		if err == nil {
			// Remove it
			return tx.Delete(&existingItem).Error
		} else if err == gorm.ErrRecordNotFound {
			return nil
		}
		return err
	}
}
