package handlers

import (
	"net/http"

	"github.com/Chak-and-Jules/home-inventory-backend/internal/i18n"
	"github.com/Chak-and-Jules/home-inventory-backend/internal/models"
	"github.com/Chak-and-Jules/home-inventory-backend/internal/utils"
	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type ShoppingListHandler struct {
	DB *gorm.DB
}

type ShoppingListItemRequest struct {
	ItemDefinitionID *uuid.UUID `json:"item_definition_id"`
	Name             string     `json:"name"`
	Quantity         float64    `json:"quantity" binding:"required,gte=0"`
}

type UpdateShoppingListItemRequest struct {
	Quantity float64 `json:"quantity" binding:"required,gte=0"`
	IsBought bool    `json:"is_bought"`
}

func (h *ShoppingListHandler) GetShoppingList(c *gin.Context) {
	homeID, ok := utils.ParseUUIDHeader(c, h.DB, "X-Home-Id", "Invalid home_id")
	if !ok {
		return
	}

	if !utils.VerifyHomeAccess(c, h.DB, homeID) {
		c.JSON(http.StatusForbidden, gin.H{"error": i18n.TranslateDB(h.DB, c, "Access denied to this home")})
		return
	}

	var items []models.ShoppingListItem
	if err := h.DB.Preload("ItemDefinition.SizeUnit").Preload("ItemDefinition.Category").Where("home_id = ?", homeID).Order("is_bought ASC, created_at DESC").Find(&items).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": i18n.TranslateDB(h.DB, c, "Failed to fetch shopping list items")})
		return
	}

	c.JSON(http.StatusOK, items)
}

func (h *ShoppingListHandler) CreateShoppingListItem(c *gin.Context) {
	homeID, ok := utils.ParseUUIDHeader(c, h.DB, "X-Home-Id", "Invalid home_id")
	if !ok {
		return
	}

	if !utils.VerifyHomeWriteAccess(c, h.DB, homeID) {
		c.JSON(http.StatusForbidden, gin.H{"error": i18n.TranslateDB(h.DB, c, "Write access denied to this home")})
		return
	}

	var req ShoppingListItemRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": i18n.TranslateDB(h.DB, c, "Invalid request payload")})
		return
	}

	if req.ItemDefinitionID == nil && req.Name == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": i18n.TranslateDB(h.DB, c, "Item definition or name is required")})
		return
	}

	name := req.Name
	if req.ItemDefinitionID != nil {
		var def models.ItemDefinition
		if err := h.DB.First(&def, *req.ItemDefinitionID).Error; err != nil {
			c.JSON(http.StatusNotFound, gin.H{"error": i18n.TranslateDB(h.DB, c, "Item definition not found")})
			return
		}
		if def.HomeID != homeID {
			c.JSON(http.StatusForbidden, gin.H{"error": i18n.TranslateDB(h.DB, c, "Item definition does not belong to this home")})
			return
		}
		if name == "" {
			name = def.Name
		}
	}

	item := models.ShoppingListItem{
		HomeID:           homeID,
		ItemDefinitionID: req.ItemDefinitionID,
		Name:             name,
		Quantity:         req.Quantity,
		IsBought:         false,
		IsAutoGenerated:  false,
	}

	if err := h.DB.Create(&item).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": i18n.TranslateDB(h.DB, c, "Failed to create shopping list item")})
		return
	}

	c.JSON(http.StatusCreated, item)
}

func (h *ShoppingListHandler) UpdateShoppingListItem(c *gin.Context) {
	id, ok := utils.ParseUUIDParam(c, h.DB, "id", "Invalid shopping list item ID")
	if !ok {
		return
	}

	var item models.ShoppingListItem
	if err := h.DB.First(&item, id).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": i18n.TranslateDB(h.DB, c, "Shopping list item not found")})
		return
	}

	if !utils.VerifyHomeWriteAccess(c, h.DB, item.HomeID) {
		c.JSON(http.StatusForbidden, gin.H{"error": i18n.TranslateDB(h.DB, c, "Write access denied to this home")})
		return
	}

	var req UpdateShoppingListItemRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": i18n.TranslateDB(h.DB, c, "Invalid request payload")})
		return
	}

	updates := map[string]interface{}{
		"quantity":  req.Quantity,
		"is_bought": req.IsBought,
	}

	if err := h.DB.Model(&item).Updates(updates).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": i18n.TranslateDB(h.DB, c, "Failed to update shopping list item")})
		return
	}

	c.JSON(http.StatusOK, gin.H{"message": i18n.TranslateDB(h.DB, c, "Shopping list item updated successfully")})
}

func (h *ShoppingListHandler) ToggleShoppingListItemBought(c *gin.Context) {
	id, ok := utils.ParseUUIDParam(c, h.DB, "id", "Invalid shopping list item ID")
	if !ok {
		return
	}

	var item models.ShoppingListItem
	if err := h.DB.First(&item, id).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": i18n.TranslateDB(h.DB, c, "Shopping list item not found")})
		return
	}

	if !utils.VerifyHomeWriteAccess(c, h.DB, item.HomeID) {
		c.JSON(http.StatusForbidden, gin.H{"error": i18n.TranslateDB(h.DB, c, "Write access denied to this home")})
		return
	}

	if err := h.DB.Model(&item).Update("is_bought", !item.IsBought).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": i18n.TranslateDB(h.DB, c, "Failed to toggle bought status")})
		return
	}

	c.JSON(http.StatusOK, gin.H{"message": i18n.TranslateDB(h.DB, c, "Shopping list item status toggled successfully")})
}

func (h *ShoppingListHandler) DeleteShoppingListItem(c *gin.Context) {
	id, ok := utils.ParseUUIDParam(c, h.DB, "id", "Invalid shopping list item ID")
	if !ok {
		return
	}

	var item models.ShoppingListItem
	if err := h.DB.First(&item, id).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": i18n.TranslateDB(h.DB, c, "Shopping list item not found")})
		return
	}

	if !utils.VerifyHomeWriteAccess(c, h.DB, item.HomeID) {
		c.JSON(http.StatusForbidden, gin.H{"error": i18n.TranslateDB(h.DB, c, "Write access denied to this home")})
		return
	}

	if err := h.DB.Delete(&models.ShoppingListItem{}, id).Error; err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": i18n.TranslateDB(h.DB, c, "Failed to delete shopping list item")})
		return
	}

	c.JSON(http.StatusOK, gin.H{"message": i18n.TranslateDB(h.DB, c, "Shopping list item deleted successfully")})
}
